services:
  fe:
    image: cheskapg/turborepo-colina:fe
    build:
      context: ./apps/fe
      dockerfile: ../../Dockerfile  # Relative path from ./apps/fe to the root Dockerfile


      args:
        PROJECTPATH: fe
        PORT: 5000
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    command: ["npm", "run", "start"]
    ports:
      - "5000:5000"
    networks:
      - app-network
  web:
    image: cheskapg/turborepo-colina:web
    build:
      context: ./apps/web
      dockerfile: ../../Dockerfile  # Relative path from ./apps/fe to the root Dockerfile
    
      args:
        PROJECTPATH: web
        PORT: 4000
    environment:
      - HOST=0.0.0.0
      - PORT=4000
    command: ["npm", "run", "start"]

    ports:
      - "4000:4000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    # external: true