version: '3.8'

services:
  fe:
    build:
      context: ./apps/fe
      dockerfile: Dockerfile.fe
      target: fe_runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run dev

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.web
      target: web_runner
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: npm run dev