services:
  fe:
    image: cheskapg/turborepo-colina:fe
    build:
      context: ./apps/fe
      args:
        PROJECTPATH: fe
        PORT: 5000
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    command: ["node", ".next/standalone/server.js", "--host", "0.0.0.0"]  # Host flag added
    ports:
      - "5000:5000"

  web:
    image: cheskapg/turborepo-colina:web
    build:
      context: ./apps/web
      args:
        PROJECTPATH: web
        PORT: 4000
    environment:
      - HOST=0.0.0.0
      - PORT=4000
    command: ["node", ".next/standalone/server.js", "--host", "0.0.0.0"]  # Host flag added
    ports:
      - "4000:4000"
