version: '3.8'

services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
      target: fe_runner
      args:
        PROJECT: fe  # Pass the PROJECT argument for fe
    ports:
      - "3000:3000"  # Map port 3000 for fe
    environment:
      - NODE_ENV=production
    command: yarn next start  # Set the default command to run the fe app

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_runner
      args:
        PROJECT: web  # Pass the PROJECT argument for web
    ports:
      - "4000:4000"  # Map port 4000 for web
    environment:
      - NODE_ENV=production
    command: yarn next start  # Set the default command to run the web app
