services:
  fe:
    image: cheskapg/turborepo-colina:fe
    build:
      context: ./apps/fe
      args:
        PROJECTPATH: fe
        PORT: 5000
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    command: ["node", ".next/standalone/apps/fe/server.js", "--host", "0.0.0.0"]
    ports:
      - "5000:5000"
    networks:
      - app-network
  web:
    image: cheskapg/turborepo-colina:web
    build:
      context: ./apps/web
      args:
        PROJECTPATH: web
        PORT: 4000
    environment:
      - HOST=0.0.0.0
      - PORT=4000
    command: ["node", ".next/standalone/apps/web/server.js", "--host", "0.0.0.0"]
    ports:
      - "4000:4000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    external: true