version: '3.8'

services:
  fe:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        APP: fe
    ports:
      - "3000:3000"
    volumes:
      - ./apps/fe:/app/apps/fe
      - /app/apps/fe/node_modules

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        APP: web
    ports:
      - "3333:3333"
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
