version: '3.8'
services:
  fe:
    build:
      context: .
      dockerfile: Dockerfile
      target: fe_runner
    ports:
      - "3000:3000"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_runner
    ports:
      - "4000:4000"
