name: Build and Push Docker Images

on:
  push:
    branches:
      - test-docker  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push FE image
        run: |
          docker build -t your-dockerhub-username/my-mono-repo:fe ./apps/fe
          docker push your-dockerhub-username/my-mono-repo:fe

      - name: Build and push WEB image
        run: |
          docker build -t your-dockerhub-username/my-mono-repo:web ./apps/web
          docker push your-dockerhub-username/my-mono-repo:web
